stages:
  - build
variables:
  DEBIAN_FRONTEND: noninteractive
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  PATH: "${CARGO_HOME}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

debian-package:
  stage: build
  image: debian:sid
  cache:
    key:
      files:
        - Cargo.lock
      prefix: sid-debian
    paths:
      - ".cargo/"
      - target/
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends eatmydata
    - eatmydata apt-get build-dep -y --no-install-recommends .
    - rm -rf dist/debian
    - scripts/deb-build --binary --no-clean
    - tests/deb/run target/lto/nala
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - dist/debian/*
