stages:
  - build
variables:
  DEBIAN_FRONTEND: noninteractive
  CACHE_COMPRESSION_LEVEL: fastest

debian-package:
  stage: build
  image: debian:sid
  parallel:
    matrix:
      - RUNNER_ARCH: [amd64, arm64]
  tags:
    - "${RUNNER_ARCH}"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-${RUNNER_ARCH}"
    fallback_keys:
      - "${CI_DEFAULT_BRANCH}-${RUNNER_ARCH}"
    paths:
      - target/
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends dpkg-dev eatmydata lintian python3 tmux whiptail
    - eatmydata apt-get build-dep -y --no-install-recommends .
    - rm -rf dist/debian
    - scripts/deb-build --binary --no-clean
    - lintian dist/debian/*.changes
    - chmod -R go-w tests/deb/packages
    - tests/deb/run debian/nala/usr/bin/nala
    - tests/deb/history/run debian/nala/usr/bin/nala
    - tests/deb/safety/run debian/nala/usr/bin/nala
    - tests/deb/term/run debian/nala/usr/bin/nala
    - tests/deb/release-info/run debian/nala/usr/bin/nala
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - dist/debian/*
