[package]
name = "nala"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://gitlab.com/volian/nala/-/tree/nala-rs"
readme = "README.rst"
description = "Commandline frontend for the APT package manager"

[dependencies]
rust-apt = { git = "https://gitlab.com/volian/rust-apt", features = ["serde"] }
# rust-apt = { path = "../rust-apt", features = ["serde"] }
tokio = { version = "1.47.1", features = ["fs", "macros", "rt-multi-thread"] }
nix = { version = "0.30.1", features = ["fs", "process", "term", "ioctl", "signal"] }
async-compression = { version = "0.4.30", features = ["tokio", "all-algorithms"] }
reqwest = { version = "0.12.23", features = ["json", "blocking"] }
serde = { version = "1.0.224", features = ["derive"] }
clap = { version = "4.5.47", features = ["derive"] }
clap_complete = { version = "4.5.58", features = ["unstable-dynamic"] }
ratatui = { version = "0.29.0", features = ["serde"] }
comfy-table = { version = "7.2.1", features = ["tty", "custom_styling"] }
mio = { version = "1.0.4", features = ["os-ext"] }
indexmap = { version = "2.11.3", features = ["serde"] }
toml = "0.9.6"
anyhow = "1.0.99"
regex = "1.11.2"
globset = "0.4.16"
serde_json = "1.0.145"
indicatif = "0.18.0"
crossterm = "0.29.0"
sha2 = "0.10.9"
digest = "0.10.7"
chrono = "0.4.42"
ansi-to-tui = "7.0.0"
bincode = "2.0.1"
tar = "0.4.44"
ar = "0.9.0"
log = { version = "0.4.28", features = ["std", "serde"] }

[build-dependencies]
clap = { version = "4.5.47", features = ["derive"] }
clap-markdown = "0.1.5"
clap_complete = { version = "4.5.58", features = ["unstable-dynamic"] }
clap_mangen = "0.2.29"

[profile.lto]
# A profile with various additional optimizations
inherits = "release"

# It isn't clear that lto makes anything faster yet
# But it does reduce the binary size. true = "fat", can also use "thin"
# This save a LOT of binary size.
lto = true

# Can't really tell if this changes anything
# This seems useless, at least in terms of file size.
# codegen-units = 1

# This causes it to not work on some machines?
# Saves about 1MB at the time of writing.
# Probably not good enough for not having the trace.
# panic = "abort"
