[package]
name = "nala"
version = "0.17.1"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://gitlab.com/volian/nala/-/tree/nala-rs"
readme = "README.md"
description = "Commandline frontend for the APT package manager"

[dependencies]
rust-apt = { version = "0.10.0", features = ["serde"] }
# rust-apt = { path = "../rust-apt", features = ["serde"] }
tokio = { version = "1.53.1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync", "time"] }
nix = { version = "0.31.3", features = ["fs", "process", "term", "ioctl", "signal", "user"] }
async-compression = { version = "0.4.42", features = ["tokio", "gzip", "xz", "zstd"] }
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
clap = { version = "4.6.4", features = ["derive"] }
clap_complete = { version = "4.6.7", features = ["unstable-dynamic"] }
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm_0_29"] }
comfy-table = { version = "7.2.2", features = ["tty", "custom_styling"] }
mio = { version = "1.2.2", features = ["os-ext"] }
indexmap = "2.14.0"
hcl = { package = "hcl-rs", version = "0.19.7" }
anyhow = "1.0.104"
regex = "1.13.1"
globset = "0.4.19"
serde_json = "1.0.151"
crossterm = "0.29.0"
sha2 = "0.11.0"
chrono = "0.4.45"
tar = { version = "0.4.46", default-features = false }
ar = "0.9.0"
fluent = "0.17.0"
unic-langid = "0.9.6"

[build-dependencies]
clap = { version = "4.6.4", features = ["derive"] }
clap_complete = { version = "4.6.7", features = ["unstable-dynamic"] }
clap_mangen = "0.3.0"

[profile.lto]
# A profile with various additional optimizations
inherits = "release"

# It isn't clear that lto makes anything faster yet
# But it does reduce the binary size. true = "fat", can also use "thin"
# This save a LOT of binary size.
lto = true

# Can't really tell if this changes anything
# This seems useless, at least in terms of file size.
# codegen-units = 1

# This causes it to not work on some machines?
# Saves about 1MB at the time of writing.
# Probably not good enough for not having the trace.
# panic = "abort"
