use std::str::FromStr;

use clap::{ArgGroup, Args, Subcommand};
use clap_complete::engine::ArgValueCompleter;

use super::completion::{history_id_completion, installed_package_completion, package_completion};
use super::flags::{AutoRemoveFlags, FixBrokenFlags, InfoFlags, InstallFlags, TransactionFlags};

/// All supported nala subcommands.
#[derive(Subcommand, Debug)]
#[clap(rename_all = "lower")]
pub enum Commands {
	List(List),
	Search(Search),
	Show(Show),
	Policy(Policy),
	Clean(Clean),
	Download(Download),
	History(History),
	Fetch(Fetch),
	Update(Update),
	Upgrade(Upgrade),
	Install(Install),
	Remove(Remove),
	AutoRemove(AutoRemove),
	#[clap(hide = true, disable_help_flag = true)]
	Moo(Moo),
}

/// List all packages or only packages based on the provided name
#[derive(Args, Debug)]
#[allow(clippy::struct_excessive_bools)]
pub struct List {
	/// Package names to search
	#[clap(required = false, add = ArgValueCompleter::new(package_completion))]
	pub pkg_names: Vec<String>,

	/// Print the full description of each package
	#[clap(long, action)]
	pub description: bool,

	/// Print the summary of each package
	#[clap(long, action)]
	pub summary: bool,

	#[clap(flatten)]
	pub info: InfoFlags,

	/// Only include packages that are installed
	#[clap(short, long, action)]
	pub installed: bool,

	/// Only include packages explicitly installed with Nala
	#[clap(short = 'N', long, action)]
	pub nala_installed: bool,

	/// Only include packages that are upgradable
	#[clap(short, long, action)]
	pub upgradable: bool,

	/// Only include virtual packages
	#[clap(short = 'V', long, action)]
	pub r#virtual: bool,

	#[clap(short = 'm', long, action)]
	pub machine: bool,
}

/// Like `List`, but uses regex and searches package descriptions.
#[derive(Args, Debug)]
pub struct Search {
	/// Search only using pkg names and not descriptions.
	#[clap(long, action)]
	pub names_only: bool,

	// Flatten list commands args into search
	#[clap(flatten)]
	pub list_args: List,
}

/// Show information about one or more packages
#[derive(Args, Debug)]
pub struct Show {
	/// Package names to show
	#[clap(required = false, add = ArgValueCompleter::new(package_completion))]
	pub pkg_names: Vec<String>,

	#[clap(flatten)]
	pub info: InfoFlags,

	#[clap(short = 'm', long, action)]
	pub machine: bool,
}

/// Show pin/priority information about one or more packages
#[derive(Args, Debug)]
pub struct Policy {
	/// Package names to show policy for
	#[clap(required = false, add = ArgValueCompleter::new(package_completion))]
	pub pkg_names: Vec<String>,

	#[clap(short = 'm', long, action)]
	pub machine: bool,
}

/// Removes the local archive of downloaded package files.
#[derive(Args, Debug)]
pub struct Clean {
	/// Removes the package lists downloaded from `update`
	#[clap(long, action)]
	pub lists: bool,

	/// Removes the `nala-sources.list` file generated by the fetch command
	#[clap(long, action)]
	pub fetch: bool,
}

/// Downloads a package to the current directory.
#[derive(Args, Debug)]
pub struct Download {
	/// Package names to download
	#[clap(add = ArgValueCompleter::new(package_completion))]
	pub pkg_names: Vec<String>,

	/// Removes the `nala-sources.list` file generated by the fetch command
	#[clap(long, action)]
	pub fetch: bool,
}

/// View or replay stored package transaction history.
#[derive(Args, Debug)]
#[clap(args_conflicts_with_subcommands = true)]
pub struct History {
	/// Show details for a specific history entry ID or `last`
	#[clap(value_name = "ID|last", add = ArgValueCompleter::new(history_id_completion))]
	pub history_id: Option<HistorySelector>,

	/// Run a history action instead of showing list/detail output
	#[clap(subcommand)]
	pub command: Option<HistoryCommand>,
}

/// Additional actions supported by the history command.
#[derive(Subcommand, Debug)]
#[clap(rename_all = "lower")]
pub enum HistoryCommand {
	Undo(HistoryTransaction),
	Redo(HistoryTransaction),
	Clear(HistoryClear),
}

/// Replay the inverse of a previously applied history entry.
#[derive(Args, Debug)]
pub struct HistoryTransaction {
	/// History entry ID or `last` to undo
	#[clap(value_name = "ID|last", add = ArgValueCompleter::new(history_id_completion))]
	pub history_id: HistorySelector,
}

/// Clear a specific stored history entry or the entire history.
#[derive(Args, Debug)]
#[clap(group(
	ArgGroup::new("target")
		.required(true)
		.args(["history_id", "all"])
))]
pub struct HistoryClear {
	/// History entry ID or `last` to clear
	#[clap(
		value_name = "ID|last",
		conflicts_with = "all",
		add = ArgValueCompleter::new(history_id_completion)
	)]
	pub history_id: Option<HistorySelector>,

	/// Clear the entire stored history
	#[clap(long, action)]
	pub all: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum HistorySelector {
	Last,
	Id(u32),
}

impl FromStr for HistorySelector {
	type Err = String;

	fn from_str(value: &str) -> Result<Self, Self::Err> {
		if value.eq_ignore_ascii_case("last") {
			return Ok(Self::Last);
		}

		value.parse::<u32>().map(Self::Id).map_err(|_| {
			format!("Invalid history selector '{value}'. Use an integer ID or 'last'.")
		})
	}
}

#[derive(Args, Debug)]
pub struct Fetch {
	#[clap(long, action)]
	pub non_free: bool,

	#[clap(long, action)]
	pub https_only: bool,

	#[clap(long, action)]
	pub sources: bool,

	#[clap(long, num_args = 0..=1, default_missing_value="3")]
	pub auto: Option<u8>,

	#[clap(short = 'c', long, action)]
	pub country: Vec<String>,

	#[clap(long, action)]
	pub debian: Option<String>,

	#[clap(long, action)]
	pub ubuntu: Option<String>,

	#[clap(long, action)]
	pub devuan: Option<String>,
}

/// Update the package lists.
#[derive(Args, Debug)]
pub struct Update {}

/// Upgrade packages.
#[derive(Args, Debug)]
#[clap(visible_aliases = ["full-upgrade", "safe-upgrade"])]
pub struct Upgrade {
	/// Prints the URIs in json and does not perform an upgrade.
	#[clap(long, action)]
	pub print_uris: bool,

	/// Exclude packages from upgrade. Accepts glob patterns.
	#[clap(long, value_name = "PKG", action, add = ArgValueCompleter::new(package_completion))]
	pub exclude: Vec<String>,

	/// Perform a Full Upgrade.
	#[clap(long, action)]
	pub full: bool,

	/// Do NOT perform a Full Upgrade.
	#[clap(long, action)]
	pub no_full: bool,

	/// Perform a Safe Upgrade.
	/// Takes precedence over other Upgrade options.
	#[clap(long, action)]
	pub safe: bool,

	#[clap(flatten)]
	pub transaction: TransactionFlags,

	#[clap(flatten)]
	pub recommends: InstallFlags,

	#[clap(flatten)]
	pub auto_remove: AutoRemoveFlags,
}

#[derive(Args, Debug)]
/// Install Packages
pub struct Install {
	/// Package names to install
	#[clap(required = false, add = ArgValueCompleter::new(package_completion))]
	pub pkg_names: Vec<String>,

	/// Reinstall packages that are already installed
	#[clap(long, action)]
	pub reinstall: bool,

	/// Set the default release to install packages from.
	#[clap(short = 't', long, value_name = "RELEASE")]
	pub target_release: Option<String>,

	#[clap(flatten)]
	pub transaction: TransactionFlags,

	#[clap(flatten)]
	pub fix_broken: FixBrokenFlags,

	#[clap(flatten)]
	pub recommends: InstallFlags,

	#[clap(flatten)]
	pub auto_remove: AutoRemoveFlags,
}

#[derive(Args, Debug)]
#[clap(visible_alias = "purge", long_about = None)]
/// Remove Packages
///
/// Using the alias `purge` is the same as running
/// `nala remove --purge`
pub struct Remove {
	/// Package names to install
	#[clap(add = ArgValueCompleter::new(installed_package_completion))]
	pub pkg_names: Vec<String>,

	#[clap(flatten)]
	pub transaction: TransactionFlags,

	#[clap(flatten)]
	pub fix_broken: FixBrokenFlags,

	#[clap(flatten)]
	pub auto_remove: AutoRemoveFlags,
}

#[derive(Args, Debug)]
#[clap(visible_alias = "autopurge", long_about = None)]
/// Automatically remove unnecessary packages
///
/// Using the alias `autopurge` is the same as running
/// `nala autoremove --purge`
pub struct AutoRemove {
	/// Additionally, when purging, remove pkgs in config state
	#[clap(long, action)]
	pub remove_config: bool,

	#[clap(flatten)]
	pub transaction: TransactionFlags,
}

#[derive(Args, Debug)]
pub struct Moo {
	#[clap(long, hide = true, action)]
	pub help: bool,

	#[clap(long, hide = true, action)]
	pub update: bool,

	#[clap(long, hide = true, action)]
	pub no_update: bool,
}
